name: hyperexecute-smartui-playwright-layout-testing-sample
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT_Username
      accessKey:
        description: LT_Access_Key
        required: true
      PROJECT_TOKEN:
        description: Smart-UI Project Token
        required: true
      sf_user: 
        description: Salesforce_username
        required: true
      sf_password:
        description: Salesforce_password
        required: true
jobs:
   #Cucumber-Sample-Hyperexeucte:
    e2e-hyperexecute:
      runs-on: ${{ matrix.os }}
      timeout-minutes: 15
      strategy:
       fail-fast: false
       matrix:
         os: [windows-latest]
      
      steps:
       - name: Checkout sources
         uses: actions/checkout@v2
         with:
          owner: vishnukdas
          repository: vishnukdas/hyperexecute-smartui-playwright-layout-testing-sample
            
       - name: Starting CLI testing
         shell: bash
         run: |
          echo "STEP 1 ) Downloading sample suite"
          #git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              #cd cucumber-selenium-hyperexecute-sample
              ls -la
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              export sf_user=${{ github.event.inputs.sf_user }}
              export sf_password=${{ github.event.inputs.sf_password }}
              export PROJECT_TOKEN=${{ github.event.inputs.PROJECT_TOKEN }}
              echo $accessKey
              echo $username
              echo $sf_user
              echo $sf_password
              echo $PROJECT_TOKEN
              ls -la
              ./hyperexecute.exe --user $LT_USERNAME --key $LT_ACCESS_KEY -i hyp-smartui-sdk.yaml --no-track

              echo "Test completion"
